# Generated by Django 2.1.1 on 2018-09-17 12:31

from django.db import migrations, models
import galeria.models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20180917_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=galeria.models.custom_upload_to, verbose_name='Foto'),
        ),
    ]
